# Copyright 2015 Kitware, Inc.
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

#  * Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.

#  * Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.

#  * Neither name of Kitware, Inc. nor the names of any contributors may be used
#    to endorse or promote products derived from this software without specific
#    prior written permission.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS''
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Part of the DARPA PPAML CP6 toolset; poc: roddy.collins@kitware.com
#

##
## implement the image indicator lookup table
##

import sys
from cp6.utilities.util import Util
from cp6.utilities.image_indicator import ImageIndicator

##
## The IILUT tracks groups and words and assigns them
## numeric IDs. Once loaded, image indicators can be
## be generated by calling repeated add_to_indicator()
## to find if the supplied string (a group ID or a text
## string) has matches in the dictionary, and setting
## the appropriate flags in the image indicator if so.
##

# McAuley keeps separate lists for groups, tags, and words. I initially
# failed to understand this, because groups and tags are loaded
# from one file (nodeFeatures) and the words are loaded from another
# (trainingText).
#
# We're mostly interested in (a) folding in the text features along
# with the existing tags, while (b) remembering if a string came from
# a tag or a text feature, yet (c) not changing the existing code much.
#
# We'll keep tag and text in a single dictionary and a single domain of
# entry IDs. It's a little inconsistent but I think it's the lowest-
# impact way to add text back in.
#

class ImageIndicatorLookupTable:

    def __init__( self ):
        self.group_text_lut = dict() # key: text, val: entry ID
        self.tag_word_text_lut = dict() # key: text, val: entry ID
        self.tag_word_text_src = dict() # key: entry ID, val: 'T' or 'W'

    def rev_lookup( self, tag, id ):
        if tag == 'G':
            for i in self.group_text_lut.iteritems():
                if (i[1] == id):
                    return i[0]
        elif (tag == 'W') or (tag == 'T') :
            for i in self.tag_word_text_lut.iteritems():
                if (i[1] == id):
                    return i[0]
        else:
            raise AssertionError('IILUT rev_lookup: bad tag "%s"\n' % tag)

        return None

    def set_from_mcauley( self, node_fn, text_features_fn, stopwords_fn ):
        stopwords = dict()
        with open( stopwords_fn ) as f:
            while 1:
                stopword = f.readline()
                if not stopword:
                    break
                stopword = stopword.strip()
                stopwords[ stopword ] = True
        sys.stderr.write('Info: read %d stopwords\n' % len(stopwords))

        n_stopwords_found = 0
        tag_word_text_index = 0
        with open( node_fn ) as f:
            header_fields = f.readline().strip().split()
            if len(header_fields) != 3:
                raise AssertionError( 'Found %d fields in header of %s; expecting 3\n' % \
                                      ( len(header_fields), node_fn ))
            (n_groups, n_tags, n_labels) = \
              (int(header_fields[0]), int(header_fields[1]), int(header_fields[2]))

            #
            # set the groups
            #

            for index in range( 0, n_groups ):
                raw_line = f.readline()
                if not raw_line:
                    raise AssertionError( 'Failed to read group line %d in %s\n' % \
                                          (index, node_fn ) )
                fields = raw_line.strip().split()
                if len(fields) != 2:
                    raise AssertionError( 'Found %d fields in group line "%s"; expecting 2\n' % \
                                          (len(fields), raw_line.strip()))
                self.group_text_lut[ fields[1] ] = index


            #
            # set the tags
            #

            for i in range( 0, n_tags ):
                raw_line = f.readline()
                if not raw_line:
                    raise AssertionError( 'Failed to read tag line %d in %s\n' % \
                                          (index, node_fn ) )
                fields = raw_line.strip().split()
                if len(fields) != 2:
                    raise AssertionError( 'Found %d fields in tag line "%s"; expecting 2\n' % \
                                          (len(fields), raw_line.strip()))

                if fields[1] in stopwords:
                    n_stopwords_found += 1
                else:
                    self.tag_word_text_lut[ fields[1] ] = tag_word_text_index
                    self.tag_word_text_src[ tag_word_text_index ] = 'T'
                    tag_word_text_index += 1


        with open( text_features_fn ) as f:
            header_fields = f.readline().strip().split()
            if len(header_fields) != 1:
                raise AssertionError( 'Found %d fields in header of %s; expecting 1\n' % \
                                      ( len(header_fields), text_fn ))
            n_words = int(header_fields[0])

            #
            # set the words
            #

            for i in range( 0, n_words ):
                raw_line = f.readline()
                if not raw_line:
                    raise AssertionError( 'Failed to read word line %d in %s\n' % \
                                          (index, text_fn ))
                fields = raw_line.strip().split()
                if len(fields) != 2:
                    raise AssertionError( 'Found %d fields in word line "%s"; expecting 2\n' % \
                                          (len(fields), raw_line.strip()))
                if fields[1] in stopwords:
                    n_stopwords_found += 1
                else:
                    self.tag_word_text_lut[ fields[1] ] = tag_word_text_index
                    self.tag_word_text_src[ tag_word_text_index ] = 'W'
                    tag_word_text_index += 1

        sys.stderr.write('Info: Found %d stopwords reading LUT\n' % n_stopwords_found)


    def add_to_indicator( self, imgind, ind_type, new_text, source_flag ):
        #
        # Given the existing image indicator imgind, look up the words in
        # new_text in the appropriate {group,word}_table. If present, record
        # it in imgind.
        #
        # groups have no 'source', they're just from groups. (If we recorded
        # the various flavors of flickr groups-- albums vs. galleries, etc-- it
        # would go here.)
        #
        # words have various sources (enumerated in the ImageIndicator flags).
        # We don't histogram how often they occur, we just flip the bits.
        #

        if not new_text:
            return
        for word in new_text.split():

            if ind_type == 'G':
                if word in self.group_text_lut:
                    entry_id = self.group_text_lut[ word ]
                    imgind.group_list[ entry_id ] = True

            elif ind_type == 'W':
                if word in self.tag_word_text_lut:
                    entry_id = self.tag_word_text_lut[ word ]
                    if not entry_id in imgind.word_list:
                        imgind.word_source_flags[ entry_id ] = ImageIndicator.IN_NONE
                    imgind.word_list[ entry_id ] = True
                    imgind.word_source_flags[ entry_id ] |= (source_flag | ImageIndicator.SRC_IS_TAG )

            else:
                raise AssertionError( 'Bad indicator type %s\n' % ind_type )

    def write_to_file( self, fn ):
        with open( fn, 'w' ) as f:
            f.write( '%d %d\n' % (len(self.group_text_lut), len(self.tag_word_text_lut)))
            for i in sorted( self.group_text_lut.iteritems(), key=lambda x:x[1] ):
                (entry_id, entry_text) = (i[1], i[0])
                f.write( '%d G %s\n' % ( entry_id, Util.qstr( entry_text )))
            for i in sorted( self.tag_word_text_lut.iteritems(), key=lambda x:x[1] ):
                (entry_id, entry_text) = (i[1], i[0])
                f.write( '%d W %s\n' % ( entry_id, Util.qstr( entry_text )))

    @staticmethod
    def read_from_file( fn ):
        t = ImageIndicatorLookupTable()
        with open( fn, 'r' ) as f:
            header_fields = Util.qstr_split( f.readline().strip() )
            if len(header_fields) != 2:
                raise AssertionError( 'ImageIndicatorLookupTable "%s": header had %d fields, expected 2' % \
                                      ( fn, len(header_fields)))
            (n_groups, n_words) = map(int, header_fields)

            for i in range(0, n_groups):
                fields = Util.qstr_split( f.readline().strip() )
                if len(fields) != 3:
                    raise AssertionError( 'ImageIndicatorLookupTable "%s": group %d had %d fields, expected 3' % \
                                          (fn, i, len(fields)))
                if fields[1] != 'G':
                    raise AssertionError( 'ImageIndicatorLookupTable "%s": entry %d flavor was %s; expected "G"' % \
                                          (fn, i, fields[1]))

                t.group_text_lut[ fields[2] ] = int( fields[0] )

            for i in range(0, n_words):
                fields = Util.qstr_split( f.readline().strip() )
                if len(fields) != 3:
                    raise AssertionError( 'ImageIndicatorLookupTable "%s": word %d had %d fields, expected 3' % \
                                          (fn, i, len(word_fields)))
                if fields[1] != 'W':
                    raise AssertionError( 'ImageIndicatorLookupTable "%s": entry %d flavor was %s; expected "T"' % \
                                          (fn, i, fields[1]))

                t.tag_word_text_lut[ fields[2] ] = int( fields[0] )

        return t

if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.stderr.write('Usage: $0 input-img-indicator-table output-img-indicator-table\n')
        sys.exit(0)
    t = ImageIndicatorTable.read_from_file( sys.argv[1] )
    sys.stderr.write('Info: image indicator table has %d grops and %d words\n' \
                     % (len(t.groups), len(t.words)))
    t.write_to_file( sys.argv[2] )
